apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hdn4hfv2d-go
  janus-idp.io/tekton: hdn4hfv2d-go
  backstage.io/kubernetes-id: hdn4hfv2d-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hdn4hfv2d-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
